version: "3"
services:
  app: 
    container_name: mavuno-app
    restart: always
    build: ./
    ports:
      - "80:8000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"